### ISSUE TITLE
extension stopped working

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CL-WebExtension#36]
Maybe it was bacuase of the new update to chrome.  I can't even load it manually.

![Screen Shot 2019-11-05 at 11 53 52 AM](https://user-images.githubusercontent.com/28393235/68228440-72b9de00-ffc3-11e9-91ba-55ca9601c27f.png)

**Comment by AddisonFreeman** [comment]
Looking into it.

**Comment by AddisonFreeman** [comment]
I’m getting them.

So it says invalid manifest.

The manifest file is like the settings file for the extension. I’m looking for any updates google has made to their standards for this file.

**Comment by AddisonFreeman** [comment]
I fixed it. The updated code is here under feature/testing: I tested it a bit on google and was able to activate a deal and all that.

https://github.com/robgpeak/CL-WebExtension/tree/feature/testing

**Comment by AddisonFreeman** [comment]
The issue was how the extension specifies that it can read cookie data from all sites. I changed the format to a more general rule but I couldn’t find where the previous one was deprecated. It could have been a bug, I’m not sure but when you update in the webstore it will autoupdate once it’s verified in about an hour.

**Comment by robgpeak** [comment]
seems to be working now.  thanks
